# Email Server Configuration (Example for Gmail)
# Important: If using Gmail, you MUST use an "App Password" rather than your normal password.
# To get an App Password: go to Google Account -> Security -> 2-Step Verification -> App passwords.
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anushkapatil6444@gmail.com
spring.mail.password=dvwl tcph yomy yiqz

# SMTP Settings
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Do not show banner on startup
spring.main.banner-mode=off
